---

- name: install borg
  apt:
    name: borgbackup
    state: present  
 
- name: mount data
  mount:
    name: /mnt/data
    src: "{{ borg.host }}:{{ borg.path }}"
    fstype: nfs
    state: mounted
